import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import SidebarComponent from "@/components/Sidebar/Sidebar";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
 return (
    <html lang="en">
      <body
        className={` ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          {/* Sidebar lateral */}
          <SidebarComponent />

          {/* Contenedor general */}
          <div className="bg-cyan-950 flex flex-col w-full min-h-screen">
            {/* Header con trigger */}
            

                <header className="flex items-center  px-4 py-2 border-gray-900 border-b bg-gray-800 shadow-sm">
              {/* Botón para abrir/cerrar sidebar */}
              <SidebarTrigger />
              <h1 className="text-lg font-semibold font-mono text-white">Crowd Chat</h1>
            </header>
           

            {/* Contenido principal */}
            <main className="flex-1 p-4">{children}</main>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
